# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# environment variables
environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1
  GO111MODULE: on

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go test -race -v ./fasturl/...

# to disable automatic tests
test: off

# to disable deployment
deploy: off
